sudo: false
dist: xenial
language: python

python:
  - "3.6-dev"
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"

notifications:
  email:
    - kostya@yandex.ru
  on_success: never # default: change
  on_failure: always # default: always

install:
  - pip install -r requirements.txt

script: python manage.py test