# Generated by Django 2.2 on 2019-04-20 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_tasker_unisender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('emailmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_tasker_unisender.EmailModel')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
            ],
            bases=('django_tasker_unisender.emailmodel',),
        ),
        migrations.CreateModel(
            name='SubscribeTest',
            fields=[
                ('emailmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_tasker_unisender.EmailModel')),
            ],
            bases=('django_tasker_unisender.emailmodel',),
        ),
    ]
