# Generated by Django 2.2 on 2019-04-18 18:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Variable to be substituted. It must be unique and case sensitive. Also, it is not recommended to create a field with the same name as the standard field names (tags, email, phone, email_status, phone_status, etc.)', max_length=78, unique=True, validators=[django.core.validators.RegexValidator(message='Use the format 0-9 a-z.', regex='^[0-9a-zA-Z]+$')], verbose_name='Name')),
                ('type', models.SmallIntegerField(choices=[(1, 'string'), (2, 'text'), (3, 'number'), (4, 'date'), (5, 'bool')], help_text='The field type is relevant only for the web interface, the controls are adjusted to the possible values. Values of different types are stored in the same way, in the text form.', verbose_name='Type')),
                ('public_name', models.CharField(help_text='Field name. If it is not used, an automatical generation by the «name» field will take place.', max_length=200, verbose_name='Public name')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('is_default', models.BooleanField(verbose_name='Default list')),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, verbose_name='Email address')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_tasker_unisender.List')),
            ],
            options={
                'verbose_name': 'Subscribe',
                'verbose_name_plural': 'Subscribes',
            },
        ),
    ]
