# Generated by Django 2.2 on 2019-04-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker_unisender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='unisender_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
