# Generated by Django 2.2 on 2019-04-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker_unisender', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together={('email', 'list')},
        ),
    ]
