# Generated by Django 2.2 on 2019-04-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker_unisender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unisendermodel',
            name='title',
        ),
        migrations.AddField(
            model_name='unisendermodel',
            name='list_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='unisendermodel',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
