# Generated by Django 2.2 on 2019-04-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker_unisender', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='list',
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
