# Generated by Django 2.2 on 2019-04-19 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker_unisender', '0002_auto_20190419_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeTest',
            fields=[
                ('unisendermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_tasker_unisender.UnisenderModel')),
            ],
            bases=('django_tasker_unisender.unisendermodel',),
        ),
        migrations.RemoveField(
            model_name='unisendermodel',
            name='list_id',
        ),
    ]
