# Generated by Django 2.2 on 2019-04-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker_unisender', '0002_auto_20190417_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='unisender_id',
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Title'),
        ),
    ]
