# Generated by Django 2.2 on 2019-04-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker_unisender', '0004_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='public_name',
            field=models.CharField(max_length=200, verbose_name='Public name'),
        ),
    ]
