# Generated by Django 2.2 on 2019-04-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker_unisender', '0005_auto_20190417_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'string'), (2, 'text'), (3, 'number'), (4, 'date'), (5, 'bool')], null=True, verbose_name='Type'),
        ),
    ]
