# Generated by Django 2.2 on 2019-04-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker_unisender', '0007_auto_20190417_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='is_default',
            field=models.BooleanField(null=True, unique=True, verbose_name='Default list'),
        ),
    ]
