# Generated by Django 2.2 on 2019-04-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker_unisender', '0008_list_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='is_default',
            field=models.NullBooleanField(unique=True, verbose_name='Default list'),
        ),
    ]
